# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: subsocial
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    ports:
      - "5432:5432"
      
  # subsocial-offchain:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  #     - "9229:9229"


# sudo su - postgres -c "createdb subsocial"
# sudo -u postgres psql -c "create user dev with encrypted password '1986';"
# sudo -u postgres psql -c "grant all privileges on database subsocial to dev;"
