# docker-compose.yml
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: subsocial-elasticsearch
    restart: on-failure
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx1024m"
      MAX_MAP_COUNT: "64000"
      discovery.type: "single-node"
      cluster.name: "subsocial-cluster"
      node.name: "subsocial-node"
      http.port: "9200"
      http.cors.enabled: "true"
      http.cors.allow-credentials: "true"
      http.cors.allow-origin: "*"
      http.cors.allow-methods: "GET"
      http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Access-Control-Allow-Headers,Accept"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    network_mode: "host"

  postgres:
    image: postgres
    container_name: subsocial-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: subsocial
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"

## IPFS Cluster #################################
#################################################

  ipfs-peer:
    image: ipfs/go-ipfs:master-latest
    container_name: subsocial-ipfs
    restart: on-failure
    ports:
      - "127.0.0.1:5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs

  cluster:
    image: ipfs/ipfs-cluster:latest
    container_name: subsocial-ipfs-cluster
    depends_on:
      - ipfs-peer
    environment:
      CLUSTER_PEERNAME: "Subsocial Cluster"
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-peer/tcp/5001
      CLUSTER_CRDT_TRUSTERPEERS: '*' # Trust all peers in Cluster (TODO: trust initial peers only)
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "127.0.0.1:9094:9094"
    volumes:
      - ./data/ipfs/cluster:/data/ipfs-cluster


#################################################

  offchain:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: dappforce/subsocial-offchain:latest
    container_name: subsocial-offchain
    depends_on:
      - postgres
      - elasticsearch
      - cluster
    restart: on-failure
    environment:
      - NODE_ENV=production
    network_mode: "host"

volumes:
  es_data:
    driver: local
  postgres_data:
    driver: local
  ipfs_staging:
    driver: local
  ipfs_data:
    driver: local
