# docker-compose.yml
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: subsocial-elasticsearch
    environment:
      - cluster.name=subsocial-cluster
      - node.name=subsocial-node
      - node.data=true
      - network.host=127.0.0.1
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Access-Control-Allow-Headers,Accept
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

  postgres:
    image: postgres
    container_name: subsocial-postgres
    environment:
      POSTGRES_DB: subsocial
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    network_mode: "host"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ipfs:
    image: ipfs/go-ipfs:master-latest
    container_name: subsocial-ipfs
    network_mode: "host"
    restart: always
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs

  subsocial-offchain:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: dappforce/subsocial-offchain:latest
    container_name: subsocial-offchain
    depends_on:
      - postgres
      - elasticsearch
      - ipfs
    environment:
      - NODE_ENV=production
    network_mode: "host"
    restart: on-failure
    volumes:
      - ~/ipfs:/data

volumes:
  es_data:
    driver: local
  postgres_data:
    driver: local
  ipfs_staging:
    driver: local
  ipfs_data:
    driver: local
